class CAI_NPCMovementStanceSettings_t
{
	// MPropertySuppressExpr = "m_bEnabled == false"
	CAI_MovementGaitSettings m_slow; // = { "m_bEnabled": true, "m_capabilities": "", "m_decelerationCurve": { "m_spline": [ { "m_flSlopeIncoming": -0.4, "m_flSlopeOutgoing": -0.4, "x": 0, "y": 1 }, { "m_flSlopeIncoming": -0.4, "m_flSlopeOutgoing": -0.4, "x": 1, "y": 0.6 } ], "m_tangents": [ { "m_nIncomingTangent": "CURVE_TANGENT_SPLINE", "m_nOutgoingTangent": "CURVE_TANGENT_SPLINE" }, { "m_nIncomingTangent": "CURVE_TANGENT_SPLINE", "m_nOutgoingTangent": "CURVE_TANGENT_SPLINE" } ], "m_vDomainMaxs": [ 1, 1 ], "m_vDomainMins": [ 0, 0.6 ] }, "m_eStrafeMode": "eContinuous", "m_flAcceleration": 150, "m_flBashStartDistance": 0, "m_flDeceleration": 500, "m_flLeanCalculationLookAheadDistance": 50, "m_flLeanSmoothingFactor": 0.05, "m_flMantleDelayRange": [ 1, 4 ], "m_flMantleStartDistance": 50, "m_flMaxIdleTurnScaleUp": 0.2, "m_flMinBashDelay": 3, "m_flMinTurnRadius": 0, "m_flMovementPlantedTurnAngleThreshold": 120, "m_flPreferredSpeed": 75, "m_flProceduralIdleTurnSpeed": 180, "m_flStartDistance": 0, "m_flStrafeTransitionAimLeftHysteresis": 20, "m_flStrafeTransitionAimRightHysteresis": 20, "m_flStrafeTransitionMinPathLength": 60, "m_hopDistanceRange": 0, "m_speedRange": 0, "m_stopDistanceRange": 0 }
	// MPropertySuppressExpr = "m_bEnabled == false"
	CAI_OptionalMovementGaitSettings m_medium; // = { "m_bEnabled": false, "m_capabilities": "", "m_decelerationCurve": { "m_spline": [ { "m_flSlopeIncoming": -0.4, "m_flSlopeOutgoing": -0.4, "x": 0, "y": 1 }, { "m_flSlopeIncoming": -0.4, "m_flSlopeOutgoing": -0.4, "x": 1, "y": 0.6 } ], "m_tangents": [ { "m_nIncomingTangent": "CURVE_TANGENT_SPLINE", "m_nOutgoingTangent": "CURVE_TANGENT_SPLINE" }, { "m_nIncomingTangent": "CURVE_TANGENT_SPLINE", "m_nOutgoingTangent": "CURVE_TANGENT_SPLINE" } ], "m_vDomainMaxs": [ 1, 1 ], "m_vDomainMins": [ 0, 0.6 ] }, "m_eStrafeMode": "eContinuous", "m_flAcceleration": 150, "m_flBashStartDistance": 0, "m_flDeceleration": 500, "m_flLeanCalculationLookAheadDistance": 50, "m_flLeanSmoothingFactor": 0.05, "m_flMantleDelayRange": [ 1, 4 ], "m_flMantleStartDistance": 50, "m_flMaxIdleTurnScaleUp": 0.2, "m_flMinBashDelay": 3, "m_flMinTurnRadius": 0, "m_flMovementPlantedTurnAngleThreshold": 120, "m_flPreferredSpeed": 100, "m_flProceduralIdleTurnSpeed": 180, "m_flStartDistance": 0, "m_flStrafeTransitionAimLeftHysteresis": 20, "m_flStrafeTransitionAimRightHysteresis": 20, "m_flStrafeTransitionMinPathLength": 60, "m_hopDistanceRange": 0, "m_speedRange": 0, "m_stopDistanceRange": 0 }
	// MPropertySuppressExpr = "m_bEnabled == false"
	CAI_OptionalMovementGaitSettings m_fast; // = { "m_bEnabled": false, "m_capabilities": "", "m_decelerationCurve": { "m_spline": [ { "m_flSlopeIncoming": -0.4, "m_flSlopeOutgoing": -0.4, "x": 0, "y": 1 }, { "m_flSlopeIncoming": -0.4, "m_flSlopeOutgoing": -0.4, "x": 1, "y": 0.6 } ], "m_tangents": [ { "m_nIncomingTangent": "CURVE_TANGENT_SPLINE", "m_nOutgoingTangent": "CURVE_TANGENT_SPLINE" }, { "m_nIncomingTangent": "CURVE_TANGENT_SPLINE", "m_nOutgoingTangent": "CURVE_TANGENT_SPLINE" } ], "m_vDomainMaxs": [ 1, 1 ], "m_vDomainMins": [ 0, 0.6 ] }, "m_eStrafeMode": "eContinuous", "m_flAcceleration": 150, "m_flBashStartDistance": 0, "m_flDeceleration": 500, "m_flLeanCalculationLookAheadDistance": 50, "m_flLeanSmoothingFactor": 0.05, "m_flMantleDelayRange": [ 1, 4 ], "m_flMantleStartDistance": 50, "m_flMaxIdleTurnScaleUp": 0.2, "m_flMinBashDelay": 3, "m_flMinTurnRadius": 0, "m_flMovementPlantedTurnAngleThreshold": 120, "m_flPreferredSpeed": 100, "m_flProceduralIdleTurnSpeed": 180, "m_flStartDistance": 0, "m_flStrafeTransitionAimLeftHysteresis": 20, "m_flStrafeTransitionAimRightHysteresis": 20, "m_flStrafeTransitionMinPathLength": 60, "m_hopDistanceRange": 0, "m_speedRange": 0, "m_stopDistanceRange": 0 }
	// MPropertySuppressExpr = "m_bEnabled == false"
	CAI_OptionalMovementGaitSettings m_veryFast; // = { "m_bEnabled": false, "m_capabilities": "", "m_decelerationCurve": { "m_spline": [ { "m_flSlopeIncoming": -0.4, "m_flSlopeOutgoing": -0.4, "x": 0, "y": 1 }, { "m_flSlopeIncoming": -0.4, "m_flSlopeOutgoing": -0.4, "x": 1, "y": 0.6 } ], "m_tangents": [ { "m_nIncomingTangent": "CURVE_TANGENT_SPLINE", "m_nOutgoingTangent": "CURVE_TANGENT_SPLINE" }, { "m_nIncomingTangent": "CURVE_TANGENT_SPLINE", "m_nOutgoingTangent": "CURVE_TANGENT_SPLINE" } ], "m_vDomainMaxs": [ 1, 1 ], "m_vDomainMins": [ 0, 0.6 ] }, "m_eStrafeMode": "eContinuous", "m_flAcceleration": 150, "m_flBashStartDistance": 0, "m_flDeceleration": 500, "m_flLeanCalculationLookAheadDistance": 50, "m_flLeanSmoothingFactor": 0.05, "m_flMantleDelayRange": [ 1, 4 ], "m_flMantleStartDistance": 50, "m_flMaxIdleTurnScaleUp": 0.2, "m_flMinBashDelay": 3, "m_flMinTurnRadius": 0, "m_flMovementPlantedTurnAngleThreshold": 120, "m_flPreferredSpeed": 100, "m_flProceduralIdleTurnSpeed": 180, "m_flStartDistance": 0, "m_flStrafeTransitionAimLeftHysteresis": 20, "m_flStrafeTransitionAimRightHysteresis": 20, "m_flStrafeTransitionMinPathLength": 60, "m_hopDistanceRange": 0, "m_speedRange": 0, "m_stopDistanceRange": 0 }
	// MPropertyFlattenIntoParentRow
	bool m_bEnabled;
};
