enum AI_FacingTargetRequestSource_t : uint32_t
{
	eInvalid = -1,
	// MPropertyFriendlyName = "Motor"
	eMotor = 0,
	// MPropertyFriendlyName = "Choreo"
	eChoreo = 1,
	// MPropertyFriendlyName = "LevelScript"
	eLevelScript = 2,
	// MPropertyFriendlyName = "Schedule"
	eSchedule = 3,
	// MPropertyFriendlyName = "Movement"
	eMovement = 4,
	// MPropertyFriendlyName = "Strategy"
	eStrategy = 5,
	// MPropertyFriendlyName = "Navigator"
	eNavigator = 6,
	// MPropertyFriendlyName = "NPC"
	eNpc = 7,
	// MPropertyFriendlyName = "Autogenerated"
	eAutogenerated = 8,
	// MPropertyFriendlyName = "Ahead"
	eAhead = 9,
	eCount = 10,
};
